---
title: "Clinical Outcomes"
output: html_document
---

```{r setup, include=FALSE}
library(stringr)
library(readxl)
library(tidyverse)
library(skimr)
library(knitr)
library(equivalence)
library(pastecs)
library(pwr)
MRIdata <- read_excel("Batch1-4_20200420.xlsx",sheet=1)
i <- c(8:48)      
MRIdata[ , i] <- apply(MRIdata[ , i], 2,            # Specify own function within apply
                    function(x) as.numeric(as.character(x)))
MRIdata<-MRIdata[-c(97:124),-c(11:36)]
MRIUniq <- MRIdata[!duplicated(MRIdata$`Patient ID`), ]
clin <- read_excel("Subtle_metadata_updated.xls",sheet=1)
clinUniq <- clin[!duplicated(clin$`Patient ID`), ]
clinical<-merge(x =MRIUniq, y = clinUniq, by="Patient ID")
clinical$amb<-ifelse(clinical$`PDDS Median`>=4, 1, 0)
clinical$higheff<-ifelse(clinical$Treatment==(c(13,15,11,16,17)), 1, 0)
clinical$cau<-ifelse(clinical$Race=="Caucasian", 1, 0)
clinical$nonhis<-ifelse(clinical$Ethnicity=="Non-Hispanic"|clinical$Ethnicity=="Non-hispanic", 1, 0)
clinical$nonhiswhite<-ifelse((clinical$Ethnicity=="Non-Hispanic" | clinical$Ethnicity=="Non-hispanic")&(clinical$Race=="Caucasian"), 1, 0)
clinical$types <- ifelse(clinical[,35]==1,1,0)
clinical$notreat <- ifelse(clinical$Treatment==99,1,0)
clinicalamb <- clinical[which(clinical$amb==1), ]
clinicalnoamb <- clinical[which(clinical$amb==0), ]
```

Overall

```{r}
options(scipen=999)
histogram(clinical$`PDDS Median`)
summarytab<-stat.desc(clinical, basic=F)
summary(clinical$`PDDS Median`)
summary(clinicalnoamb$`PDDS Median`)
summary(clinicalamb$`PDDS Median`)
sd(clinical$`PDDS Median`)
sd(clinicalnoamb$`PDDS Median`)
sd(clinicalamb$`PDDS Median`)
summary(clinical$`Age (at first scan)`)
summary(clinicalnoamb$`Age (at first scan)`)
summary(clinicalamb$`Age (at first scan)`)
sd(clinical$`Age (at first scan)`)
sd(clinicalnoamb$`Age (at first scan)`)
sd(clinicalamb$`Age (at first scan)`)
summary(clinical$`MSRS-R Median`)
summary(clinicalnoamb$`MSRS-R Median`)
summary(clinicalamb$`MSRS-R Median`)
summary(clinical$`Disease Duration (date of MRI - date of first symptoms), years`)
summary(clinicalnoamb$`Disease Duration (date of MRI - date of first symptoms), years`)
summary(clinicalamb$`Disease Duration (date of MRI - date of first symptoms), years`)
sd(clinical$`Disease Duration (date of MRI - date of first symptoms), years`)
sd(clinicalnoamb$`Disease Duration (date of MRI - date of first symptoms), years`)
sd(clinicalamb$`Disease Duration (date of MRI - date of first symptoms), years`)
summarytabamb<-stat.desc(clinicalamb,basic=F)
summarytabnoamb<-stat.desc(clinicalnoamb,basic=F)
table(clinical$Sex)
table(clinicalnoamb$Sex)
table(clinicalamb$Sex)
prop.table(table(clinical$Sex))
prop.table(table(clinicalnoamb$Sex))
prop.table(table(clinicalamb$Sex))
table(clinical$Race)
table(clinicalnoamb$Race)
table(clinicalamb$Race)
prop.table(table(clinical$Race))
prop.table(table(clinicalnoamb$Race))
prop.table(table(clinicalamb$Race))
table(clinical$nonhis)
table(clinicalnoamb$nonhis)
table(clinicalamb$nonhis)
prop.table(table(clinical$nonhis))
prop.table(table(clinicalnoamb$nonhis))
prop.table(table(clinicalamb$nonhis))
table(clinical$types)
table(clinicalnoamb$types)
table(clinicalamb$types)
prop.table(table(clinical$types))
prop.table(table(clinicalnoamb$types))
prop.table(table(clinicalamb$types))
table(clinical$notreat)
table(clinicalnoamb$notreat)
table(clinicalamb$notreat)
prop.table(table(clinical$notreat))
prop.table(table(clinicalnoamb$notreat))
prop.table(table(clinicalamb$notreat))
table(clinical$higheff)
table(clinicalnoamb$higheff)
table(clinicalamb$higheff)
prop.table(table(clinical$higheff))
prop.table(table(clinicalnoamb$higheff))
prop.table(table(clinicalamb$higheff))
table(clinical$nonhiswhite)
table(clinicalnoamb$nonhiswhite)
table(clinicalamb$nonhiswhite)
prop.table(table(clinical$nonhiswhite))
prop.table(table(clinicalnoamb$nonhiswhite))
prop.table(table(clinicalamb$nonhiswhite))
```

<!-- Statiatical tests - Overall -->

<!-- Used Wilcoxon Rank Sum test and Fischer Exact test for categorical variables -->
<!-- ```{r} -->
<!-- wilcox.test(`Age (at first scan)` ~ amb, data=clinical) -->
<!-- sextbl = table(clinical$Sex,clinical$amb) -->
<!-- sextbl -->
<!-- fisher.test(sextbl) -->
<!-- racetbl = table(clinical$cau,clinical$amb) -->
<!-- racetbl -->
<!-- fisher.test(racetbl) -->
<!-- histbl = table(clinical$nonhis,clinical$amb) -->
<!-- histbl -->
<!-- fisher.test(histbl) -->
<!-- wilcox.test( `MSRS-R Median` ~ amb, data=clinical) -->
<!-- typestbl = table(clinical$types,clinical$amb) -->
<!-- typestbl -->
<!-- fisher.test(typestbl) -->
<!-- wilcox.test( `Disease Duration (date of MRI - date of first symptoms), years` ~ amb, data=clinical) -->
<!-- wilcox.test( `MSRS-R Median` ~ amb, data=clinical) -->
<!-- notreattbl = table(clinical$notreat,clinical$amb) -->
<!-- notreattbl -->
<!-- fisher.test(notreattbl) -->
<!-- highefftbl = table(clinical$higheff,clinical$amb) -->
<!-- highefftbl -->
<!-- fisher.test(highefftbl) -->
<!-- nonhiswhitetbl = table(clinical$nonhiswhite,clinical$amb) -->
<!-- nonhiswhitetbl -->
<!-- fisher.test(nonhiswhitetbl) -->
<!-- ``` -->
MRI metrics
```{r}
mean(MRIdata$T2LV_Conv, na.rm = TRUE)
sd(MRIdata$T2LV_Conv, na.rm = TRUE)
mean(MRIdata$NBV_Conv, na.rm = TRUE)
sd(MRIdata$NBV_Conv, na.rm = TRUE)
mean(MRIdata$NBV_Subtle, na.rm = TRUE)
sd(MRIdata$NBV_Subtle, na.rm = TRUE)
mean(MRIdata$NBV_SubtleMR, na.rm = TRUE)
sd(MRIdata$NBV_SubtleMR, na.rm = TRUE)
mean(MRIdata$NThV_Conv, na.rm = TRUE)
sd(MRIdata$NThV_Conv, na.rm = TRUE)
mean(MRIdata$NThV_Subtle, na.rm = TRUE)
sd(MRIdata$NThV_Subtle, na.rm = TRUE)
mean(MRIdata$NThV_SubtleMR, na.rm = TRUE)
sd(MRIdata$NThV_SubtleMR, na.rm = TRUE)
mean(MRIdata$NGMV_Conv, na.rm = TRUE)
sd(MRIdata$NGMV_Conv, na.rm = TRUE)
mean(MRIdata$NGMV_Subtle, na.rm = TRUE)
sd(MRIdata$NGMV_Subtle, na.rm = TRUE)
mean(MRIdata$NGMV_SubtleMR, na.rm = TRUE)
sd(MRIdata$NGMV_SubtleMR, na.rm = TRUE)
mean(MRIdata$NWMV_Conv, na.rm = TRUE)
sd(MRIdata$NWMV_Conv, na.rm = TRUE)
mean(MRIdata$NWMV_Subtle, na.rm = TRUE)
sd(MRIdata$NWMV_Subtle, na.rm = TRUE)
mean(MRIdata$NWMV_SubtleMR, na.rm = TRUE)
sd(MRIdata$NWMV_SubtleMR, na.rm = TRUE)
```
```{r}
median(MRIdata$NBV_Conv, na.rm = TRUE)
IQR(MRIdata$NBV_Conv, na.rm = TRUE)
median(MRIdata$NBV_Subtle, na.rm = TRUE)
IQR(MRIdata$NBV_Subtle, na.rm = TRUE)
median(MRIdata$NBV_SubtleMR, na.rm = TRUE)
IQR(MRIdata$NBV_SubtleMR, na.rm = TRUE)
median(MRIdata$NThV_Conv, na.rm = TRUE)
IQR(MRIdata$NThV_Conv, na.rm = TRUE)
median(MRIdata$NThV_Subtle, na.rm = TRUE)
IQR(MRIdata$NThV_Subtle, na.rm = TRUE)
median(MRIdata$NThV_SubtleMR, na.rm = TRUE)
IQR(MRIdata$NThV_SubtleMR, na.rm = TRUE)
median(MRIdata$NGMV_Conv, na.rm = TRUE)
IQR(MRIdata$NGMV_Conv, na.rm = TRUE)
median(MRIdata$NGMV_Subtle, na.rm = TRUE)
IQR(MRIdata$NGMV_Subtle, na.rm = TRUE)
median(MRIdata$NGMV_SubtleMR, na.rm = TRUE)
IQR(MRIdata$NGMV_SubtleMR, na.rm = TRUE)
median(MRIdata$NWMV_Conv, na.rm = TRUE)
IQR(MRIdata$NWMV_Conv, na.rm = TRUE)
median(MRIdata$NWMV_Subtle, na.rm = TRUE)
IQR(MRIdata$NWMV_Subtle, na.rm = TRUE)
median(MRIdata$NWMV_SubtleMR, na.rm = TRUE)
IQR(MRIdata$NWMV_SubtleMR, na.rm = TRUE)
```

```{r}
((mean(MRIdata$NBV_Subtle, na.rm = TRUE) - mean(MRIdata$NBV_Conv, na.rm = TRUE))/ mean(MRIdata$NBV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NBV_Subtle, na.rm = TRUE) - mean(MRIdata$NBV_Conv, na.rm = TRUE)
((mean(MRIdata$NThV_Subtle, na.rm = TRUE) - mean(MRIdata$NThV_Conv, na.rm = TRUE))/mean(MRIdata$NThV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NThV_Subtle, na.rm = TRUE) - mean(MRIdata$NThV_Conv, na.rm = TRUE)
((mean(MRIdata$NGMV_Subtle, na.rm = TRUE) - mean(MRIdata$NGMV_Conv, na.rm = TRUE))/mean(MRIdata$NGMV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NGMV_Subtle, na.rm = TRUE) - mean(MRIdata$NGMV_Conv, na.rm = TRUE)
((mean(MRIdata$NWMV_Subtle, na.rm = TRUE) - mean(MRIdata$NWMV_Conv, na.rm = TRUE))/mean(MRIdata$NWMV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NWMV_Subtle, na.rm = TRUE) - mean(MRIdata$NWMV_Conv, na.rm = TRUE)

((mean(MRIdata$T2LV_SubtleMR, na.rm = TRUE) - mean(MRIdata$T2LV_Conv, na.rm = TRUE))/ mean(MRIdata$T2LV_Conv, na.rm = TRUE)) * 100
(mean(MRIdata$T2LV_SubtleMR, na.rm = TRUE) - mean(MRIdata$T2LV_Conv, na.rm = TRUE))

((mean(MRIdata$NBV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NBV_Conv, na.rm = TRUE))/ mean(MRIdata$NBV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NBV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NBV_Conv, na.rm = TRUE)

((mean(MRIdata$NThV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NThV_Conv, na.rm = TRUE))/mean(MRIdata$NThV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NThV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NThV_Conv, na.rm = TRUE)

((mean(MRIdata$NGMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NGMV_Conv, na.rm = TRUE))/mean(MRIdata$NGMV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NGMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NGMV_Conv, na.rm = TRUE)

((mean(MRIdata$NWMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NWMV_Conv, na.rm = TRUE))/mean(MRIdata$NWMV_Conv, na.rm = TRUE)) * 100
mean(MRIdata$NWMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NWMV_Conv, na.rm = TRUE)

((mean(MRIdata$T2LV_SubtleMR, na.rm = TRUE) - mean(MRIdata$T2LV_Subtle, na.rm = TRUE))/ mean(MRIdata$T2LV_Subtle, na.rm = TRUE)) * 100
(mean(MRIdata$T2LV_SubtleMR, na.rm = TRUE) - mean(MRIdata$T2LV_Subtle, na.rm = TRUE))

((mean(MRIdata$NBV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NBV_Subtle, na.rm = TRUE))/ mean(MRIdata$NBV_Subtle, na.rm = TRUE)) * 100
abs(mean(MRIdata$NBV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NBV_Subtle, na.rm = TRUE))

((mean(MRIdata$NThV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NThV_Subtle, na.rm = TRUE))/mean(MRIdata$NThV_Subtle, na.rm = TRUE)) * 100
mean(MRIdata$NThV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NThV_Subtle, na.rm = TRUE)

((mean(MRIdata$NGMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NGMV_Subtle, na.rm = TRUE))/mean(MRIdata$NGMV_Subtle, na.rm = TRUE)) * 100
mean(MRIdata$NGMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NGMV_Subtle, na.rm = TRUE)

((mean(MRIdata$NWMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NWMV_Subtle, na.rm = TRUE))/mean(MRIdata$NWMV_Subtle, na.rm = TRUE)) * 100
mean(MRIdata$NWMV_SubtleMR, na.rm = TRUE) - mean(MRIdata$NWMV_Subtle, na.rm = TRUE)
```

```{r}
boxplot(MRIdata$NBV_Conv)$out
boxplot(MRIdata$NThV_Conv)$out
boxplot(MRIdata$NGMV_Conv)$out
boxplot(MRIdata$NWMV_Conv)$out

boxplot(MRIdata$NBV_Subtle)$out
boxplot(MRIdata$NThV_Subtle)$out
boxplot(MRIdata$NGMV_Subtle)$out
boxplot(MRIdata$NWMV_Subtle)$out

boxplot(MRIdata$NBV_SubtleMR)$out
boxplot(MRIdata$NThV_SubtleMR)$out
boxplot(MRIdata$NGMV_SubtleMR)$out
boxplot(MRIdata$NWMV_SubtleMR)$out
```



Paired t-tests for NBV
```{r}
t.test(MRIdata$NBV_Subtle,MRIdata$NBV_Conv, paired=TRUE)
mean(MRIdata$NBV_Subtle-MRIdata$NBV_Conv,na.rm=TRUE)
sd(MRIdata$NBV_Subtle-MRIdata$NBV_Conv,na.rm=TRUE)
t.test(MRIdata$NBV_SubtleMR,MRIdata$NBV_Conv, paired=TRUE)
mean(MRIdata$NBV_SubtleMR-MRIdata$NBV_Conv,na.rm=TRUE)
sd(MRIdata$NBV_SubtleMR-MRIdata$NBV_Conv,na.rm=TRUE)
t.test(MRIdata$NBV_SubtleMR,MRIdata$NBV_Subtle, paired=TRUE)
mean(MRIdata$NBV_SubtleMR-MRIdata$NBV_Subtle,na.rm=TRUE)
sd(MRIdata$NBV_SubtleMR-MRIdata$NBV_Subtle,na.rm=TRUE)
```
NThV
```{r}
t.test(MRIdata$NThV_Subtle,MRIdata$NThV_Conv, paired=TRUE)
mean(MRIdata$NThV_Subtle-MRIdata$NThV_Conv,na.rm=TRUE)
sd(MRIdata$NThV_Subtle-MRIdata$NThV_Conv,na.rm=TRUE)
t.test(MRIdata$NThV_SubtleMR,MRIdata$NThV_Conv, paired=TRUE)
mean(MRIdata$NThV_SubtleMR-MRIdata$NThV_Conv,na.rm=TRUE)
sd(MRIdata$NThV_SubtleMR-MRIdata$NThV_Conv,na.rm=TRUE)
t.test(MRIdata$NThV_SubtleMR,MRIdata$NThV_Subtle, paired=TRUE)
mean(MRIdata$NThV_SubtleMR-MRIdata$NThV_Subtle,na.rm=TRUE)
sd(MRIdata$NThV_SubtleMR-MRIdata$NThV_Subtle,na.rm=TRUE)
```

NGMV
```{r}
t.test(MRIdata$NGMV_Subtle,MRIdata$NGMV_Conv, paired=TRUE)
mean(MRIdata$NGMV_Subtle-MRIdata$NGMV_Conv,na.rm=TRUE)
sd(MRIdata$NGMV_Subtle-MRIdata$NGMV_Conv,na.rm=TRUE)
t.test(MRIdata$NGMV_SubtleMR,MRIdata$NGMV_Conv, paired=TRUE)
mean(MRIdata$NGMV_SubtleMR-MRIdata$NGMV_Conv,na.rm=TRUE)
sd(MRIdata$NGMV_SubtleMR-MRIdata$NGMV_Conv,na.rm=TRUE)
t.test(MRIdata$NGMV_SubtleMR,MRIdata$NGMV_Subtle, paired=TRUE)
mean(MRIdata$NGMV_SubtleMR-MRIdata$NGMV_Subtle,na.rm=TRUE)
sd(MRIdata$NGMV_SubtleMR-MRIdata$NGMV_Subtle,na.rm=TRUE)
```
NWMV
```{r}
t.test(MRIdata$NWMV_Subtle,MRIdata$NWMV_Conv, paired=TRUE)
mean(MRIdata$NWMV_Subtle-MRIdata$NWMV_Conv,na.rm=TRUE)
sd(MRIdata$NWMV_Subtle-MRIdata$NWMV_Conv,na.rm=TRUE)
t.test(MRIdata$NWMV_SubtleMR,MRIdata$NWMV_Conv, paired=TRUE)
mean(MRIdata$NWMV_SubtleMR-MRIdata$NWMV_Conv,na.rm=TRUE)
sd(MRIdata$NWMV_SubtleMR-MRIdata$NWMV_Conv,na.rm=TRUE)
t.test(MRIdata$NWMV_SubtleMR,MRIdata$NWMV_Subtle, paired=TRUE)
mean(MRIdata$NWMV_SubtleMR-MRIdata$NWMV_Subtle,na.rm=TRUE)
sd(MRIdata$NWMV_SubtleMR-MRIdata$NWMV_Subtle,na.rm=TRUE)
```

T2LV
```{r}
t.test(MRIdata$T2LV_Subtle,MRIdata$T2LV_Conv, paired=TRUE)
mean(MRIdata$T2LV_Subtle-MRIdata$T2LV_Conv,na.rm=TRUE)
sd(MRIdata$T2LV_Subtle-MRIdata$T2LV_Conv,na.rm=TRUE)
t.test(MRIdata$T2LV_SubtleMR,MRIdata$T2LV_Conv, paired=TRUE)
mean(MRIdata$T2LV_SubtleMR-MRIdata$T2LV_Conv,na.rm=TRUE)
sd(MRIdata$T2LV_SubtleMR-MRIdata$T2LV_Conv,na.rm=TRUE)
t.test(MRIdata$T2LV_SubtleMR,MRIdata$T2LV_Subtle, paired=TRUE)
mean(MRIdata$T2LV_SubtleMR-MRIdata$T2LV_Subtle,na.rm=TRUE)
sd(MRIdata$T2LV_SubtleMR-MRIdata$T2LV_Subtle,na.rm=TRUE)
```

```{r}
ES.t.paired(md = -748.7241 , sd =2603.505, n = 29, t =-1.5487, se = NULL,
df = 28, alternative = "two.sided")
pwr.t.test(d=0.2875831,power=0.8,sig.level=0.05,type="paired",alternative="two.sided")

ES.t.paired(md = -591.6485 , sd =3039.31, n = 30, t =-1.0662, se = NULL,
df = 29, alternative = "two.sided")
pwr.t.test(d=0.1946654,power=0.8,sig.level=0.05,type="paired",alternative="two.sided")

ES.t.paired(md = 120.8205, sd =2596.767, n = 29, t =0.25056, se = NULL,
df = 28, alternative = "two.sided")
pwr.t.test(d=0.04652728,power=0.8,sig.level=0.05,type="paired",alternative="two.sided")

pwr.t.test(n=30, d=0.2875831,sig.level=0.05,type="paired",alternative="two.sided")
pwr.t.test(n=30, d=0.1946654,sig.level=0.05,type="paired",alternative="two.sided")
pwr.t.test(n=30, d=0.04652728,sig.level=0.05,type="paired",alternative="two.sided")
```


